"""pitch added to comment

Revision ID: 38edc501adc5
Revises: 8b8483b65b0a
Create Date: 2020-05-02 21:04:59.365702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38edc501adc5'
down_revision = '8b8483b65b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
