"""created a new table for Pitch

Revision ID: 4d7b860bfce9
Revises: 8e1112c5cfe1
Create Date: 2020-05-04 06:56:06.458263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d7b860bfce9'
down_revision = '8e1112c5cfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch', sa.String(), nullable=True),
    sa.Column('pitch_category', sa.String(length=20), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitch', ['pitch_id'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'pitch')
    op.drop_column('users', 'downvotes')
    op.drop_column('users', 'pitch_category')
    op.drop_column('users', 'posted')
    op.drop_column('users', 'pitch')
    op.drop_column('users', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('pitch_category', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'pitch_id')
    op.drop_table('pitch')
    # ### end Alembic commands ###
