"""added posted column

Revision ID: 60a0f78be642
Revises: be4dc002790a
Create Date: 2020-05-03 12:22:29.664765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a0f78be642'
down_revision = 'be4dc002790a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'posted')
    # ### end Alembic commands ###
