"""added a pitch

Revision ID: 8b8483b65b0a
Revises: a23f1f555f81
Create Date: 2020-05-01 22:05:01.162549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8483b65b0a'
down_revision = 'a23f1f555f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch', sa.String(), nullable=True))
    op.drop_column('comments', 'pitch_id')
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'pitch')
    # ### end Alembic commands ###
