"""added a pitch_id

Revision ID: a23f1f555f81
Revises: b3350dad0be5
Create Date: 2020-05-01 21:52:25.340680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23f1f555f81'
down_revision = 'b3350dad0be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_column('comments', 'pitch')
    op.add_column('users', sa.Column('pitch_id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pitch_id')
    op.add_column('comments', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
