"""added pitch_category

Revision ID: be4dc002790a
Revises: 3ac43c193bb3
Create Date: 2020-05-03 10:04:19.031865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4dc002790a'
down_revision = '3ac43c193bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_category', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pitch_category')
    # ### end Alembic commands ###
